### ISSUE TITLE
请求详细的安装文档

### ISSUE THREAD

**Issue by ixmu** [NullPointerMaker/telegram-cn-ostra-bot#1]
debian9环境下
按照提示安装，执行报错started
tail: invalid PID: ‘’

**Comment by NullPointerMaker** [comment]
Git 里只有代码，没有二进制，需要用 IDE 或 Maven 编译打包。  
旧版打包好的二进制可执行文件可在 Telegram 频道里获取。  
新版可在 GitHub 的 Release 获取。
